version: '3.8'

services:

  web:
    container_name: loginweb6
    build: .
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code 
    ports:
      - '8000:8000'
    expose:
      - '8000'
    #links:
    #  - mysql

  mysql:
    container_name: logindb6
    image: 'mysql:5.7'
    volumes:
      - './database/data:/var/lib/mysql'
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: loginDB
      MYSQL_HOST: 172.17.0.1 
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PORT: 33060
